# Generated by Django 3.1.5 on 2021-01-20 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entrey_date',
            new_name='entry_date',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entrey_text',
            new_name='entry_text',
        ),
    ]
